name = "scoure-football"
main = "./worker.js"
compatibility_date = "2025-06-21"
compatibility_flags = ["nodejs_compat"]

# Configure for Next.js application
[build]
  command = "npm run build"

# Configure assets for the static files
[site]
  bucket = "./.next/static"

# Configure environment variables
[vars]
  PUPPETEER_CACHE_DIR = "/tmp/puppeteer-cache"

# Note: Resource limits are not configurable on the free plan